#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

#2. Print the NUMPY version and the configuration.

In [2]:
print(np.__version__)

1.19.2


In [3]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/usuario/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/usuario/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/usuario/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/usuario/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/usuario/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/usuario/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/usuario/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/usuario/opt/anaconda3/include']
None


#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?





In [4]:
a = matriz=np.random.random((2, 3, 5))
a

array([[[0.29887754, 0.85688017, 0.83907532, 0.80438118, 0.58879593],
        [0.37498144, 0.90216838, 0.26458048, 0.69327613, 0.05773663],
        [0.0152354 , 0.44260049, 0.29653574, 0.02686964, 0.27160964]],

       [[0.16386077, 0.45921261, 0.68182539, 0.83909555, 0.7416329 ],
        [0.60073868, 0.55598458, 0.96297694, 0.81017867, 0.87305606],
        [0.62812296, 0.65969158, 0.77510829, 0.27008989, 0.4517053 ]]])

#4. Print a.

In [5]:
a

array([[[0.29887754, 0.85688017, 0.83907532, 0.80438118, 0.58879593],
        [0.37498144, 0.90216838, 0.26458048, 0.69327613, 0.05773663],
        [0.0152354 , 0.44260049, 0.29653574, 0.02686964, 0.27160964]],

       [[0.16386077, 0.45921261, 0.68182539, 0.83909555, 0.7416329 ],
        [0.60073868, 0.55598458, 0.96297694, 0.81017867, 0.87305606],
        [0.62812296, 0.65969158, 0.77510829, 0.27008989, 0.4517053 ]]])

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [6]:
b =array = np.ones ((5, 3, 2))

array

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#6. Print b.

In [7]:
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
a.size

30

In [9]:
b.size

30

In [10]:
a.size == b.size 

True

#8. Are you able to add a and b? Why or why not?

In [11]:
np.array([a,b])

<ipython-input-11-964832cdcfcd>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([a,b])


array([array([[[0.29887754, 0.85688017, 0.83907532, 0.80438118, 0.58879593],
        [0.37498144, 0.90216838, 0.26458048, 0.69327613, 0.05773663],
        [0.0152354 , 0.44260049, 0.29653574, 0.02686964, 0.27160964]],

       [[0.16386077, 0.45921261, 0.68182539, 0.83909555, 0.7416329 ],
        [0.60073868, 0.55598458, 0.96297694, 0.81017867, 0.87305606],
        [0.62812296, 0.65969158, 0.77510829, 0.27008989, 0.4517053 ]]]),
       array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])], dtype=object)

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [12]:
c = b.transpose(2,1,0)

c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
print (c.shape)
print (a.shape)
print (d.shape)

(2, 3, 5)
(2, 3, 5)


NameError: name 'd' is not defined

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [25]:
d = a+c
d

array([[[1.29887754, 1.85688017, 1.83907532, 1.80438118, 1.58879593],
        [1.37498144, 1.90216838, 1.26458048, 1.69327613, 1.05773663],
        [1.0152354 , 1.44260049, 1.29653574, 1.02686964, 1.27160964]],

       [[1.16386077, 1.45921261, 1.68182539, 1.83909555, 1.7416329 ],
        [1.60073868, 1.55598458, 1.96297694, 1.81017867, 1.87305606],
        [1.62812296, 1.65969158, 1.77510829, 1.27008989, 1.4517053 ]]])

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [29]:
print (a);  print (d)

[[[0.29887754 0.85688017 0.83907532 0.80438118 0.58879593]
  [0.37498144 0.90216838 0.26458048 0.69327613 0.05773663]
  [0.0152354  0.44260049 0.29653574 0.02686964 0.27160964]]

 [[0.16386077 0.45921261 0.68182539 0.83909555 0.7416329 ]
  [0.60073868 0.55598458 0.96297694 0.81017867 0.87305606]
  [0.62812296 0.65969158 0.77510829 0.27008989 0.4517053 ]]]
[[[1.29887754 1.85688017 1.83907532 1.80438118 1.58879593]
  [1.37498144 1.90216838 1.26458048 1.69327613 1.05773663]
  [1.0152354  1.44260049 1.29653574 1.02686964 1.27160964]]

 [[1.16386077 1.45921261 1.68182539 1.83909555 1.7416329 ]
  [1.60073868 1.55598458 1.96297694 1.81017867 1.87305606]
  [1.62812296 1.65969158 1.77510829 1.27008989 1.4517053 ]]]


#12. Multiply a and c. Assign the result to e

In [30]:
e = a*c
e

array([[[0.29887754, 0.85688017, 0.83907532, 0.80438118, 0.58879593],
        [0.37498144, 0.90216838, 0.26458048, 0.69327613, 0.05773663],
        [0.0152354 , 0.44260049, 0.29653574, 0.02686964, 0.27160964]],

       [[0.16386077, 0.45921261, 0.68182539, 0.83909555, 0.7416329 ],
        [0.60073868, 0.55598458, 0.96297694, 0.81017867, 0.87305606],
        [0.62812296, 0.65969158, 0.77510829, 0.27008989, 0.4517053 ]]])

#13. Does e equal to a? Why or why not?

In [ ]:
# Si son iguales

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [39]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean ()

print (d_max)
print (d_min)
print (d_mean)

1.9629769437682492
1.0152353968909424
1.5402294760014084


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [ ]:
f = 

In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.