In [3]:
import numpy as np

In [4]:
np.version.version

'1.19.2'

In [5]:
a = np.random.random((2,3,5))

In [6]:
a

array([[[0.95488883, 0.5352634 , 0.31059417, 0.74508684, 0.97688017],
        [0.19463748, 0.5022628 , 0.97437251, 0.75395419, 0.3581806 ],
        [0.66474204, 0.5335506 , 0.67711696, 0.20224224, 0.88108493]],

       [[0.56410228, 0.4256948 , 0.69016312, 0.62020059, 0.14525813],
        [0.1334849 , 0.46578438, 0.08769199, 0.91430162, 0.47395915],
        [0.45155184, 0.79858003, 0.03740097, 0.96239602, 0.84598788]]])

In [7]:
b = np.ones((5,2,3))

In [8]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
b.shape

b.size

30

In [10]:
a.size   # Si tienen la misma 'size'

30

In [11]:
a.size == b.size

True

In [12]:
np.add(a, b) #No se pueden sumar, sus dimensiones no son válidas para la suma

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
b.transpose((1,2,0))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
c= b.transpose((1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [15]:
np.add(a, c)

array([[[1.95488883, 1.5352634 , 1.31059417, 1.74508684, 1.97688017],
        [1.19463748, 1.5022628 , 1.97437251, 1.75395419, 1.3581806 ],
        [1.66474204, 1.5335506 , 1.67711696, 1.20224224, 1.88108493]],

       [[1.56410228, 1.4256948 , 1.69016312, 1.62020059, 1.14525813],
        [1.1334849 , 1.46578438, 1.08769199, 1.91430162, 1.47395915],
        [1.45155184, 1.79858003, 1.03740097, 1.96239602, 1.84598788]]])

In [16]:
d = np.add(a, c)

In [17]:
a

array([[[0.95488883, 0.5352634 , 0.31059417, 0.74508684, 0.97688017],
        [0.19463748, 0.5022628 , 0.97437251, 0.75395419, 0.3581806 ],
        [0.66474204, 0.5335506 , 0.67711696, 0.20224224, 0.88108493]],

       [[0.56410228, 0.4256948 , 0.69016312, 0.62020059, 0.14525813],
        [0.1334849 , 0.46578438, 0.08769199, 0.91430162, 0.47395915],
        [0.45155184, 0.79858003, 0.03740097, 0.96239602, 0.84598788]]])

In [18]:
d

array([[[1.95488883, 1.5352634 , 1.31059417, 1.74508684, 1.97688017],
        [1.19463748, 1.5022628 , 1.97437251, 1.75395419, 1.3581806 ],
        [1.66474204, 1.5335506 , 1.67711696, 1.20224224, 1.88108493]],

       [[1.56410228, 1.4256948 , 1.69016312, 1.62020059, 1.14525813],
        [1.1334849 , 1.46578438, 1.08769199, 1.91430162, 1.47395915],
        [1.45155184, 1.79858003, 1.03740097, 1.96239602, 1.84598788]]])

In [19]:
# La diferencia es que a, es la matriz sin modificar creada aleatoriamente, y la matriz d, ha sumado la matriz a con la matriz b transformada en c para poder conseguir las mismas dimensiones y así sumarlas correctamente

In [20]:
np.multiply(a, c)

array([[[0.95488883, 0.5352634 , 0.31059417, 0.74508684, 0.97688017],
        [0.19463748, 0.5022628 , 0.97437251, 0.75395419, 0.3581806 ],
        [0.66474204, 0.5335506 , 0.67711696, 0.20224224, 0.88108493]],

       [[0.56410228, 0.4256948 , 0.69016312, 0.62020059, 0.14525813],
        [0.1334849 , 0.46578438, 0.08769199, 0.91430162, 0.47395915],
        [0.45155184, 0.79858003, 0.03740097, 0.96239602, 0.84598788]]])

In [21]:
e= np.multiply(a, c)

In [22]:
a == c

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [23]:
# No son iguales porque no son True (Yona answer)

In [24]:
d.min() 

1.037400973077177

In [25]:
d_min=d.min() 

In [26]:
d.max()

1.976880168639687

In [27]:
d_max=d.max()

In [28]:
d.mean()

1.5627138492496395

In [29]:
d_mean=d.mean()

In [30]:
f = np.empty_like((d))

In [31]:
f

array([[[0.95488883, 0.5352634 , 0.31059417, 0.74508684, 0.97688017],
        [0.19463748, 0.5022628 , 0.97437251, 0.75395419, 0.3581806 ],
        [0.66474204, 0.5335506 , 0.67711696, 0.20224224, 0.88108493]],

       [[0.56410228, 0.4256948 , 0.69016312, 0.62020059, 0.14525813],
        [0.1334849 , 0.46578438, 0.08769199, 0.91430162, 0.47395915],
        [0.45155184, 0.79858003, 0.03740097, 0.96239602, 0.84598788]]])

In [32]:
for i in range(d.shape[0]):
    for k in range(d.shape[1]):
        for x in range(d.shape[2]):
            if d[i][k][x] > d_min and d[i][k][x]< d_mean:
                f[i][k][x] = 25
            elif d[i][k][x] > d_mean and d[i][k][x] < d_max:
                f[i][k][x]= 75
            elif d[i][k][x] == d_mean:
                f[i][k][x] = 50
            elif d[i][k][x] == d_min:
                f[i][k][x]== 0
            elif d[i][k][x] == d_max:
                f[i][k][x]== 100
print (f)


      

[[[7.50000000e+01 2.50000000e+01 2.50000000e+01 7.50000000e+01
   9.76880169e-01]
  [2.50000000e+01 2.50000000e+01 7.50000000e+01 7.50000000e+01
   2.50000000e+01]
  [7.50000000e+01 2.50000000e+01 7.50000000e+01 2.50000000e+01
   7.50000000e+01]]

 [[7.50000000e+01 2.50000000e+01 7.50000000e+01 7.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 2.50000000e+01 2.50000000e+01 7.50000000e+01
   2.50000000e+01]
  [2.50000000e+01 7.50000000e+01 3.74009731e-02 7.50000000e+01
   7.50000000e+01]]]
