In [1]:
import numpy as np

In [3]:
np.version.version

'1.19.2'

In [4]:
a = np.random.random((2,3,5))

In [5]:
a

array([[[0.81269282, 0.50439647, 0.64292998, 0.42332816, 0.37383977],
        [0.44101304, 0.38442064, 0.81379474, 0.75196211, 0.04636043],
        [0.75025422, 0.35822693, 0.08275498, 0.91139137, 0.50776247]],

       [[0.30104003, 0.13325382, 0.72972707, 0.48267566, 0.9248193 ],
        [0.83458682, 0.16882516, 0.71936474, 0.89143097, 0.10773344],
        [0.06326856, 0.59696833, 0.36165773, 0.84564405, 0.26223102]]])

In [45]:
b = np.ones((5,2,3))

In [46]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
b.shape

b.size

30

In [48]:
a.size   # Si tienen la misma 'size'

30

In [66]:
a.size == b.size

True

In [50]:
np.add(a, b) #No se pueden sumar, sus dimensiones no son válidas para la suma

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [51]:
b.transpose((1,2,0))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [53]:
c= b.transpose((1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [54]:
np.add(a, c)

array([[[1.81269282, 1.50439647, 1.64292998, 1.42332816, 1.37383977],
        [1.44101304, 1.38442064, 1.81379474, 1.75196211, 1.04636043],
        [1.75025422, 1.35822693, 1.08275498, 1.91139137, 1.50776247]],

       [[1.30104003, 1.13325382, 1.72972707, 1.48267566, 1.9248193 ],
        [1.83458682, 1.16882516, 1.71936474, 1.89143097, 1.10773344],
        [1.06326856, 1.59696833, 1.36165773, 1.84564405, 1.26223102]]])

In [55]:
d = np.add(a, c)

In [56]:
a

array([[[0.81269282, 0.50439647, 0.64292998, 0.42332816, 0.37383977],
        [0.44101304, 0.38442064, 0.81379474, 0.75196211, 0.04636043],
        [0.75025422, 0.35822693, 0.08275498, 0.91139137, 0.50776247]],

       [[0.30104003, 0.13325382, 0.72972707, 0.48267566, 0.9248193 ],
        [0.83458682, 0.16882516, 0.71936474, 0.89143097, 0.10773344],
        [0.06326856, 0.59696833, 0.36165773, 0.84564405, 0.26223102]]])

In [57]:
d

array([[[1.81269282, 1.50439647, 1.64292998, 1.42332816, 1.37383977],
        [1.44101304, 1.38442064, 1.81379474, 1.75196211, 1.04636043],
        [1.75025422, 1.35822693, 1.08275498, 1.91139137, 1.50776247]],

       [[1.30104003, 1.13325382, 1.72972707, 1.48267566, 1.9248193 ],
        [1.83458682, 1.16882516, 1.71936474, 1.89143097, 1.10773344],
        [1.06326856, 1.59696833, 1.36165773, 1.84564405, 1.26223102]]])

In [32]:
# La diferencia es que a, es la matriz sin modificar creada aleatoriamente, y la matriz d, ha sumado la matriz a con la matriz b transformada en c para poder conseguir las mismas dimensiones y así sumarlas correctamente

In [58]:
np.multiply(a, c)

array([[[0.81269282, 0.50439647, 0.64292998, 0.42332816, 0.37383977],
        [0.44101304, 0.38442064, 0.81379474, 0.75196211, 0.04636043],
        [0.75025422, 0.35822693, 0.08275498, 0.91139137, 0.50776247]],

       [[0.30104003, 0.13325382, 0.72972707, 0.48267566, 0.9248193 ],
        [0.83458682, 0.16882516, 0.71936474, 0.89143097, 0.10773344],
        [0.06326856, 0.59696833, 0.36165773, 0.84564405, 0.26223102]]])

In [67]:
e= np.multiply(a, c)

In [68]:
a == c

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [36]:
# No son iguales porque no son True (Yona answer)

In [69]:
d.min() 

1.0463604325901055

In [41]:
d_min:d.min() 

In [62]:
d.max()

1.9248192997348315

In [63]:
d_max=d.max()

In [64]:
d.mean()

1.5076118281182582

In [65]:
d_mean=d.mean()

In [82]:
f = np.empty_like((d))

In [84]:
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])