In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
print (np)

<module 'numpy' from '/Users/joseignacioacasocastro/opt/anaconda3/envs/clase/lib/python3.8/site-packages/numpy/__init__.py'>


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
a=np.empty((2,3,5))

In [4]:
#4. Print a.
print (a)

[[[-1.72723371e-077 -1.72723371e-077  7.41098469e-323  0.00000000e+000
    8.50389957e-001]
  [ 1.16097020e-028  1.68890874e-052  4.17451856e-057  8.97190388e-067
    5.01163173e+217]
  [ 8.37170074e-144  1.00588661e-070  1.14195126e-071  5.28110520e-091
    9.35587710e-067]]

 [[ 5.01163119e+217  5.49419094e-143  9.80058441e+252  7.50189709e+247
    1.35617292e+248]
  [ 7.83892484e-067  2.38235493e+179  1.03979916e-042  2.69899405e-056
    9.85297404e+165]
  [ 5.04621361e+180  8.37170571e-144  9.30350598e+199  5.60230216e-067
    2.08600674e-308]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
b = np.ones((5, 2, 3))

In [6]:
#6. Print b.
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
b.size == a.size

True

In [8]:
#8. Are you able to add a and b? Why or why not?
#No, they have different dimensions.

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))
print (c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print (d)

[[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.85038996e+000]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   5.01163173e+217]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.00000000e+000]]

 [[5.01163119e+217 1.00000000e+000 9.80058441e+252 7.50189709e+247
   1.35617292e+248]
  [1.00000000e+000 2.38235493e+179 1.00000000e+000 1.00000000e+000
   9.85297404e+165]
  [5.04621361e+180 1.00000000e+000 9.30350598e+199 1.00000000e+000
   1.00000000e+000]]]


In [12]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[-1.72723371e-077 -1.72723371e-077  7.41098469e-323  0.00000000e+000
    8.50389957e-001]
  [ 1.16097020e-028  1.68890874e-052  4.17451856e-057  8.97190388e-067
    5.01163173e+217]
  [ 8.37170074e-144  1.00588661e-070  1.14195126e-071  5.28110520e-091
    9.35587710e-067]]

 [[ 5.01163119e+217  5.49419094e-143  9.80058441e+252  7.50189709e+247
    1.35617292e+248]
  [ 7.83892484e-067  2.38235493e+179  1.03979916e-042  2.69899405e-056
    9.85297404e+165]
  [ 5.04621361e+180  8.37170571e-144  9.30350598e+199  5.60230216e-067
    2.08600674e-308]]]
[[[1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.85038996e+000]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   5.01163173e+217]
  [1.00000000e+000 1.00000000e+000 1.00000000e+000 1.00000000e+000
   1.00000000e+000]]

 [[5.01163119e+217 1.00000000e+000 9.80058441e+252 7.50189709e+247
   1.35617292e+248]
  [1.00000000e+000 2.38235493e+179 1.00000000e+000 1.00000000e+000
   9.85297404e+165]
  [5.04

In [13]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)

In [14]:
#13. Does e equal to a? Why or why not?
print (e)

[[[-1.72723371e-077 -1.72723371e-077  7.41098469e-323  0.00000000e+000
    8.50389957e-001]
  [ 1.16097020e-028  1.68890874e-052  4.17451856e-057  8.97190388e-067
    5.01163173e+217]
  [ 8.37170074e-144  1.00588661e-070  1.14195126e-071  5.28110520e-091
    9.35587710e-067]]

 [[ 5.01163119e+217  5.49419094e-143  9.80058441e+252  7.50189709e+247
    1.35617292e+248]
  [ 7.83892484e-067  2.38235493e+179  1.03979916e-042  2.69899405e-056
    9.85297404e+165]
  [ 5.04621361e+180  8.37170571e-144  9.30350598e+199  5.60230216e-067
    2.08600674e-308]]]


In [15]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.amax(d)
d_min = np.min(d)
d_mean = np.mean(d)
print (d_max)
print (d_min)
print (d_mean)

9.80058440676548e+252
1.0
3.2669316810096147e+251


In [16]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2,3,5])
print (f)

[[[-1.72723371e-077 -1.72723371e-077  7.41098469e-323  0.00000000e+000
    8.50389957e-001]
  [ 1.16097020e-028  1.68890874e-052  4.17451856e-057  8.97190388e-067
    5.01163173e+217]
  [ 8.37170074e-144  1.00588661e-070  1.14195126e-071  5.28110520e-091
    9.35587710e-067]]

 [[ 5.01163119e+217  5.49419094e-143  9.80058441e+252  7.50189709e+247
    1.35617292e+248]
  [ 7.83892484e-067  2.38235493e+179  1.03979916e-042  2.69899405e-056
    9.85297404e+165]
  [ 5.04621361e+180  8.37170571e-144  9.30350598e+199  5.60230216e-067
    2.08600674e-308]]]
