# 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [2]:
np.version.version

'1.20.2'

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a". Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.random((2,3,5)) # method 1
from numpy import random
a1 = random.randint(100,size=(2,5,3)) # method 2
a2 = random.rand(2, 5, 3) # method 3

# 4. Print a.

In [4]:
print(a)

[[[0.61835338 0.4318822  0.3321428  0.6003409  0.50504851]
  [0.27231101 0.6494446  0.80877892 0.01853542 0.01876546]
  [0.39762229 0.69896694 0.9910836  0.37221002 0.82257278]]

 [[0.88116733 0.05073404 0.99497705 0.0896365  0.49318418]
  [0.02213988 0.45213365 0.01392262 0.34545535 0.15921214]
  [0.89587807 0.44441276 0.75688532 0.75088648 0.03803041]]]


# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [5]:
b = np.ones((5,2,3))

# 6. Print b.

In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
a.size == b.size

True

# 8. Are you able to add a and b? Why or why not?

In [8]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#answer: even though the two structures have the same size/ numbers of elements (30), they can't be added as they have different dimensions as stated above

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [9]:
c = b.transpose(1,2,0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [10]:
d =np.add(a,c)
print(d)
#Structures have the same dimensions (x, y, z)

[[[1.61835338 1.4318822  1.3321428  1.6003409  1.50504851]
  [1.27231101 1.6494446  1.80877892 1.01853542 1.01876546]
  [1.39762229 1.69896694 1.9910836  1.37221002 1.82257278]]

 [[1.88116733 1.05073404 1.99497705 1.0896365  1.49318418]
  [1.02213988 1.45213365 1.01392262 1.34545535 1.15921214]
  [1.89587807 1.44441276 1.75688532 1.75088648 1.03803041]]]


# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print(a)

[[[0.61835338 0.4318822  0.3321428  0.6003409  0.50504851]
  [0.27231101 0.6494446  0.80877892 0.01853542 0.01876546]
  [0.39762229 0.69896694 0.9910836  0.37221002 0.82257278]]

 [[0.88116733 0.05073404 0.99497705 0.0896365  0.49318418]
  [0.02213988 0.45213365 0.01392262 0.34545535 0.15921214]
  [0.89587807 0.44441276 0.75688532 0.75088648 0.03803041]]]


In [12]:
print(d)

[[[1.61835338 1.4318822  1.3321428  1.6003409  1.50504851]
  [1.27231101 1.6494446  1.80877892 1.01853542 1.01876546]
  [1.39762229 1.69896694 1.9910836  1.37221002 1.82257278]]

 [[1.88116733 1.05073404 1.99497705 1.0896365  1.49318418]
  [1.02213988 1.45213365 1.01392262 1.34545535 1.15921214]
  [1.89587807 1.44441276 1.75688532 1.75088648 1.03803041]]]


In [13]:
# if d = a + c, then d - a = c as one can observe above

# 12. Multiply a and c. Assign the result to e.

In [14]:
e = a*c

# 13. Does e equal to a? Why or why not?

In [15]:
e == a

#Because c is a structure with 1 only, and as this is the neutral element of multiplication, one should expect the equality

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [16]:
print('max = ', d.max(), 'min = ', d.min(), 'mean = ', d.mean())

max =  1.994977054877265 min =  1.013922619592621 mean =  1.464223820730275


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [17]:
f= np.empty((2,3,5))
print(f) # it's empty, it uses a memory saved as values. Therefore, the numbers below do not represent f

[[[1.61835338 1.4318822  1.3321428  1.6003409  1.50504851]
  [1.27231101 1.6494446  1.80877892 1.01853542 1.01876546]
  [1.39762229 1.69896694 1.9910836  1.37221002 1.82257278]]

 [[1.88116733 1.05073404 1.99497705 1.0896365  1.49318418]
  [1.02213988 1.45213365 1.01392262 1.34545535 1.15921214]
  [1.89587807 1.44441276 1.75688532 1.75088648 1.03803041]]]


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question

In [40]:
print('max = ', d.max(), 'min = ', d.min(), 'mean = ', d.mean())
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d)

max =  1.994977054877265 min =  1.013922619592621 mean =  1.464223820730275
[[[1.61835338 1.4318822  1.3321428  1.6003409  1.50504851]
  [1.27231101 1.6494446  1.80877892 1.01853542 1.01876546]
  [1.39762229 1.69896694 1.9910836  1.37221002 1.82257278]]

 [[1.88116733 1.05073404 1.99497705 1.0896365  1.49318418]
  [1.02213988 1.45213365 1.01392262 1.34545535 1.15921214]
  [1.89587807 1.44441276 1.75688532 1.75088648 1.03803041]]]


In [41]:

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d.mean():
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d.mean():
                f[i][j][k] = 50
            elif f[i][j][k] == d_max:
                f[i][j][k] = 100
print(f)            

[[[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  25. 100.  25.  75.]
  [ 25.  25.   0.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]


# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [45]:
f=f.astype(str)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] > d_min and d[i][j][k] < d.mean():
                f[i][j][k] = 'A'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 'B'
            elif d[i][j][k] == d_min:
                f[i][j][k] = 'C'
            elif d[i][j][k] == d.mean():
                f[i][j][k] = 'D'
            elif f[i][j][k] == d_max:
                f[i][j][k] = 'E'
print(f)  

[[['B' 'A' 'A' 'B' 'B']
  ['A' 'B' 'B' 'A' 'A']
  ['A' 'B' 'B' 'A' 'B']]

 [['B' 'A' '100.0' 'A' 'B']
  ['A' 'A' 'C' 'A' 'A']
  ['B' 'A' 'B' 'B' 'A']]]
